/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_ValueArg */

#ifndef _Included_opencl_executor_ValueArg
#define _Included_opencl_executor_ValueArg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencl_executor_ValueArg
 * Method:    create
 * Signature: (F)Lopencl/executor/ValueArg;
 */
JNIEXPORT jobject JNICALL Java_opencl_executor_ValueArg_create__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     opencl_executor_ValueArg
 * Method:    create
 * Signature: (I)Lopencl/executor/ValueArg;
 */
JNIEXPORT jobject JNICALL Java_opencl_executor_ValueArg_create__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     opencl_executor_ValueArg
 * Method:    create
 * Signature: (D)Lopencl/executor/ValueArg;
 */
JNIEXPORT jobject JNICALL Java_opencl_executor_ValueArg_create__D
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
