/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_Kernel */

#ifndef _Included_opencl_executor_Kernel
#define _Included_opencl_executor_Kernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencl_executor_Kernel
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lopencl/executor/Kernel;
 */
JNIEXPORT jobject JNICALL Java_opencl_executor_Kernel_create
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     opencl_executor_Kernel
 * Method:    build
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opencl_executor_Kernel_build
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
