/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_JNIHandle */

#ifndef _Included_opencl_executor_JNIHandle
#define _Included_opencl_executor_JNIHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencl_executor_JNIHandle
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opencl_executor_JNIHandle_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
