/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_LocalArg */

#ifndef _Included_opencl_executor_LocalArg
#define _Included_opencl_executor_LocalArg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencl_executor_LocalArg
 * Method:    create
 * Signature: (I)Lopencl/executor/LocalArg;
 */
JNIEXPORT jobject JNICALL Java_opencl_executor_LocalArg_create
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
