/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_KernelArg */

#ifndef _Included_opencl_executor_KernelArg
#define _Included_opencl_executor_KernelArg
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
