CREATE TABLE IF NOT EXISTS lift_results_pool(
  id int NOT NULL AUTO_INCREMENT,
  batches int,
  images int,
  imagesize int,
  input_channels int,
  kernelsize_l0 int,
  kernelsize_l1 int,
  kernelstride_l0 int,
  kernelstride_l1 int,
  elsperthread_l0 int,
  elsperthread_l1 int,
  inputtilesize_l0 int,
  inputtilesize_l1 int,
  ran boolean NOT NULL,
  abort_reason varchar(1000),
  success boolean,
  runtime_l0 float,
  runtime_l1 float,
  experiment_id int,
  datetime DATETIME,
  PRIMARY KEY (id)
);