#include <lift_numpy/librad2deg.cpp>
#include <lift_numpy/libarcsin.cpp>
#include <lift_numpy/libdegrees.cpp>
#include <lift_numpy/libhypot.cpp>
#include <lift_numpy/libcosh.cpp>
#include <lift_numpy/libcos.cpp>
#include <lift_numpy/libradians.cpp>
#include <lift_numpy/libsinh.cpp>
#include <lift_numpy/libdeg2rad.cpp>
#include <lift_numpy/libarctan2.cpp>
#include <lift_numpy/libsin.cpp>
#include <lift_numpy/libarctan.cpp>
#include <lift_numpy/libtan.cpp>
#include <lift_numpy/libarccos.cpp>
