echo "*** Layer config ***"
echo "inputChannels -> 3, inputWidth -> 224, inputHeight -> 224,"
echo "padFuncX -> 1, padFuncY -> 1,"
echo "kernelWidth -> 3, kernelHeight -> 3,"
echo "kernelStrideX -> 1, kernelStrideY -> 1,"
echo "numKernels -> 64"
echo "*** Rewrite point params *** "
echo "tiling_hook_ABTiling.cacheAaddressSpace -> Some(global), tiling_hook_ABTiling.cacheBaddressSpace -> Some(global), tiling_hook_ABTiling.orderOfCacheADims -> None, tiling_hook_ABTiling.orderOfCacheBDims -> Some(List(0, 1))"
echo "tiling_hook_ABTiling.vectorizeTileALoad_Vectorize.vectorLen -> None"
echo "tiling_hook_ABTiling.vectorizeTileBLoad_Vectorize.vectorLen -> None"
echo "divideAndConquerHook_DivideAndConquer.conquerFun_0_Privatize.resultAddressSpace -> Some(global)"
echo "caching_hook_ABTiling.cacheAaddressSpace -> None, caching_hook_ABTiling.cacheBaddressSpace -> Some(global), caching_hook_ABTiling.orderOfCacheADims -> None, caching_hook_ABTiling.orderOfCacheBDims -> Some(List(0, 1))"
echo "caching_hook_ABTiling.vectorizeTileALoad_Vectorize.vectorLen -> None"
echo "caching_hook_ABTiling.vectorizeTileBLoad_Vectorize.vectorLen -> None"
echo "partReduceAccPrivatize_hook_Privatize.resultAddressSpace -> Some(global)"
echo "partReduceVectorize_hook_Vectorize.vectorLen -> None"
echo "*** Rewrite pass params *** "
echo "mapTransform.24.p28727 -> Some(Map(f) => MapWrg(f))"
echo "mapTransform.25.p27097 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.26.p39346 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.30.p38098 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.31.p12612 -> Some(AbstractMap1(AbstractMap2(f)) => Split(I) o AbstractMap1(f) o Join())"
echo "mapTransform.32.p367 -> Some(Map(f) => MapLcl(f))"
echo "mapTransform.33.p46359 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.34.p4293 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.84.p31952 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.103.p15192 -> Some(Map(f) => MapLcl(f))"
echo "mapTransform.104.p2195 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.105.p16215 -> Some(AbstractMap1(AbstractMap2(f)) => Split(I) o AbstractMap1(f) o Join())"
echo "mapTransform.108.p33074 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.109.p23178 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.110.p52014 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.111.p53131 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.138.p36710 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.139.p54298 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.140.p32075 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.141.p24190 -> Some(AbstractMap1(AbstractMap2(f)) => Split(I) o AbstractMap1(f) o Join())"
echo "mapTransform.142.p18797 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.209.p17509 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.210.p8362 -> Some(Map(f) => MapLcl(f))"
echo "mapTransform.211.p28868 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.212.p52545 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.213.p47300 -> Some(AbstractMap1(AbstractMap2(f)) => Split(I) o AbstractMap1(f) o Join())"
echo "mapTransform.223.p12657 -> Some(Map(f) => MapLcl(f))"
echo "mapTransform.224.p27607 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.225.p53252 -> Some(Map(f) => MapSeq(f))"
echo "mapTransform.226.p16583 -> Some(AbstractMap1(AbstractMap2(f)) => Split(I) o AbstractMap1(f) o Join())"
echo "*** Tuning params ***"
echo "tileWidth -> 32, tileHeight -> 224, tileDepth -> 1,"
echo "kernelGroupSize -> 1,"
echo "inputCacheSizeX -> 8, inputCacheSizeY -> 16,"
echo "kernelCacheSize -> 1"
echo "localSize0 -> 223"
echo "localSize1 -> 1"
echo "localSize2 -> 1"
echo "nWrgs0 -> 64"
echo "nWrgs1 -> 1"
echo "nWrgs2 -> 1"

echo "Generated on 2020-07-27-16-34-00"
g++ ./test_harness.cpp -I. -o ./a.out -std=c++11 -lOpenCL -I/home/shunya/armnn-onnx/ComputeLibrary/include -L/usr/lib/aarch64-linux/gnu/ -lmali -D INPUT_CHANNELS=3 -D INPUT_WIDTH=224 -D INPUT_HEIGHT=224 -D PAD_FUNC_X=1 -D PAD_FUNC_Y=1 -D KERNEL_WIDTH=3 -D KERNEL_HEIGHT=3 -D KERNEL_STRIDE_X=1 -D KERNEL_STRIDE_Y=1 -D NUM_KERNELS=64$TRIALS -Wno-ignored-attributes
./a.out .
