/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_Executor_ExecutorFailureException */

#ifndef _Included_opencl_executor_Executor_ExecutorFailureException
#define _Included_opencl_executor_Executor_ExecutorFailureException
#ifdef __cplusplus
extern "C" {
#endif
#undef opencl_executor_Executor_ExecutorFailureException_serialVersionUID
#define opencl_executor_Executor_ExecutorFailureException_serialVersionUID -3042686055658047285LL
#undef opencl_executor_Executor_ExecutorFailureException_serialVersionUID
#define opencl_executor_Executor_ExecutorFailureException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
