/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_Executor */

#ifndef _Included_opencl_executor_Executor
#define _Included_opencl_executor_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencl_executor_Executor
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIIII[Lopencl/executor/KernelArg;)D
 */
JNIEXPORT jdouble JNICALL Java_opencl_executor_Executor_execute
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     opencl_executor_Executor
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_opencl_executor_Executor_init__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     opencl_executor_Executor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opencl_executor_Executor_init__
  (JNIEnv *, jclass);

/*
 * Class:     opencl_executor_Executor
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opencl_executor_Executor_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
