/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencl_executor_Executor */

#ifndef _Included_opencl_executor_Executor
#define _Included_opencl_executor_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencl_executor_Executor
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;II[Lopencl/executor/KernelArg;)V
 */
JNIEXPORT void JNICALL Java_opencl_executor_Executor_execute
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
