#!/bin/bash

SCRIPT_FOLDER=`dirname $0`
TOP_FOLDER="${1}Cl"

find $TOP_FOLDER -type d | sed 's/Cl\//Ptx\//g' | xargs mkdir -p

find $TOP_FOLDER -name "*.csv" | xargs -n1 -P0 $SCRIPT_FOLDER/copyCsv

find $TOP_FOLDER -name "*.cl" | xargs -n1 -P0 $SCRIPT_FOLDER/compile

